let temp = [1,2,3,'red','blue',true];
console.log(temp);
console.log(typeof(temp));
temp[10] = 'hello';
console.log(temp);
console.log(temp.length);
console.log(temp.push('cat'));
console.log(temp);
console.log(temp.pop());
console.log(temp.shift());
console.log(temp.unshift("oliver"));
console.log([].pop());
console.log(temp);
let t1 = [1,2,3];
let t2 = [4,5,6];
console.log(t1.concat(t2));
console.log(t1);
console.log(t1.includes(1));
console.log(t1.reverse());
console.log(t1);
console.log(temp.slice(5));
console.log(temp.slice(0,6));
console.log(temp.slice(-3));
temp.splice(6,4,"yellow");
console.log(temp);
temp.splice(7,0,"blah","blah");
console.log(temp);